image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mhutchie.git-graph
    - streetsidesoftware.code-spell-checker
    - Dart-Code.dart-code

tasks:
  - name: start
    command: pub run ./main.dart
